// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using xZAPP.Core;

namespace xZAPP.iOS
{
	public partial class ReportListViewController : UITableViewController
	{
        Client client;

		public ReportListViewController (IntPtr handle) : base (handle)
		{
		}

        public override void DidReceiveMemoryWarning()
        {
            // Releases the view if it doesn't have a superview.
            base.DidReceiveMemoryWarning();

            // Release any cached data, images, etc that aren't in use.
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            // Perform any additional setup after loading the view, typically from a nib.
            var addButton = new UIBarButtonItem(UIBarButtonSystemItem.Stop, Logout);
            NavigationItem.RightBarButtonItem = addButton;


            ConfigureView();
        }

        public void SetClient(Client cl)
        {
            if (client != cl)
            {
                client = cl;

                // Update the view
                ConfigureView();
            }
        }           

        void ConfigureView()
        {

            // Update the user interface for the detail item
            if (IsViewLoaded && client != null)
            {
                this.Title = client.clientNameFormal;

                // TODO Create a UITableView with the dagrapportage for selected client
            }
        }

        private void Logout(object sender, EventArgs args)
        {       
            this.PerformSegue("logoutFromReports", this);
        }
	}
}
