// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace xZAPP.iOS
{
	public partial class ReportDetailViewController : UIViewController
	{
		public ReportDetailViewController (IntPtr handle) : base (handle)
		{
		}

        public override void DidReceiveMemoryWarning()
        {
            // Releases the view if it doesn't have a superview.
            base.DidReceiveMemoryWarning();

            // Release any cached data, images, etc that aren't in use.
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            // Perform any additional setup after loading the view, typically from a nib.
            var addButton = new UIBarButtonItem(UIBarButtonSystemItem.Stop, Logout);
            NavigationItem.RightBarButtonItem = addButton;
                       
        }


        private void Logout(object sender, EventArgs args)
        {       
            this.PerformSegue("logoutFromReportDetail", this);
        }
	}
}
